name: Trigger Sync

on:
  repository_dispatch:
    types: [main_updated]

jobs:
  trigger-sync:
    if: github.repository == 'yulrang/ci-cd-copied'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git user
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
      - name: Sync fork
        run: |
          git remote add upstream https://github.com/subject-test-26/ci-cd.git
          git fetch upstream
          git checkout master
          git merge upstream/master --allow-unrelated-histories || true
          git add .
          git commit -m "Resolve merge conflicts" || echo "No changes to commit"
          git push origin master