name: Trigger Sync

on:
  repository_dispatch:
    types: [main_updated]

jobs:
  trigger-sync:
    if: github.repository == 'yulrang/ci-cd-copied'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync fork
        run: |
          git remote add upstream https://github.com/subject-test-26/ci-cd.git
          git fetch upstream
          git checkout master
          git merge upstream/master 
          git push origin master